spring.application.name=projetCIL


server.port=8080

logging.level.org.springframework=error
logging.level.root=error
logging.level.com.openclassroom=info

logging.level.org.springframework.boot.web.embedded.tomcat=INFO


# cannextion avc postgree sgl
spring.datasource.url=jdbc:postgresql://localhost:5432/model
spring.datasource.username=postgres
spring.datasource.password=lorie66

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect